version: '3.1'

services:
  db:
    image: wuchentian/csscholars-db
    restart: always
    environment:
      POSTGRES_DB: csscholars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
